# Render.com Deployment Configuration
# This file defines the infrastructure for Quiet Craft Solutions and should be in the root of your repository.

databases:
  - name: quiet-craft-db
    plan: "Standard"
    databaseName: quiet_craft_production
    user: quiet_craft_user
    region: oregon

services:
  - type: web
    name: quiet-craft-backend
    runtime: node
    env: node
    plan: standard
    # The root directory for the backend service, relative to the repo root
    rootDir: quiet-craft-backend/quiet-craft-backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: quiet-craft-db
          property: connectionString
      - key: FRONTEND_URL
        # This dynamically uses the URL of the deployed frontend service
        value: ${{services.quiet-craft-frontend.url}}
      # Clerk Authentication (set in dashboard)
      - key: CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLERK_JWT_KEY
        sync: false
      # OpenRouter AI (set in dashboard)
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_MODEL
        value: anthropic/claude-3-haiku
      - key: OPENROUTER_FALLBACK_MODEL
        value: openai/gpt-3.5-turbo
      # Google Maps API (set in dashboard)
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      # Pricing Configuration
      - key: BASE_DELIVERY_FEE
        value: "75.00"
      - key: DISTANCE_TIER_1_MAX
        value: "20"
      - key: DISTANCE_TIER_2_MAX
        value: "50"
      - key: DISTANCE_TIER_1_RATE
        value: "0.00"
      - key: DISTANCE_TIER_2_RATE
        value: "1.50"
      - key: DISTANCE_TIER_3_RATE
        value: "2.00"
      # Item Fees
      - key: SMALL_ITEM_FEE
        value: "10.00"
      - key: MEDIUM_ITEM_FEE
        value: "25.00"
      - key: LARGE_ITEM_FEE
        value: "50.00"
      # Service Fees
      - key: SAME_DAY_FEE
        value: "50.00"
      - key: NEXT_DAY_FEE
        value: "25.00"
      - key: STANDARD_FEE
        value: "0.00"
      - key: EMERGENCY_BASE_FEE
        value: "150.00"
      - key: EMERGENCY_MULTIPLIER
        value: "2.0"
      # System Configuration
      - key: SUPER_ADMIN_IDS
        sync: false
      - key: TAX_RATE
        value: "0.085"
      - key: ENABLE_ANALYTICS
        value: "true"
      - key: ENABLE_CACHING
        value: "true"
      - key: LOG_LEVEL
        value: info

  - type: web
    name: quiet-craft-frontend
    runtime: static
    # The root directory for the frontend service, relative to the repo root
    rootDir: quiet-craft-website-redesigned
    buildCommand: echo "No build command needed for static site"
    staticPublishPath: .
    headers:
      - path: "/*"
        name: "X-Frame-Options"
        value: "DENY"
      - path: "/*"
        name: "X-Content-Type-Options"
        value: "nosniff"
      - path: "/*"
        name: "Referrer-Policy"
        value: "strict-origin-when-cross-origin"
      - path: "/*"
        name: "Permissions-Policy"
        value: "camera=(), microphone=(), geolocation=()"
    routes:
      - type: rewrite
        source: /api/*
        # This dynamically proxies requests to the backend service
        destination: ${{services.quiet-craft-backend.url}}/api/:path*
      - type: rewrite
        source: /*
        destination: /index.html

    # Build filter to only trigger builds on backend changes
    buildFilter:
      paths:
        - "**/*.js"
        - "package.json"
        - "package-lock.json"
      ignoredPaths:
        - "node_modules/**"
        - "logs/**"
        - "*.log"
